### ISSUE TITLE
A_Qg variations

### ISSUE THREAD

**Issue by giacomomagni** [niclaurenti/adani#22]
@niclaurenti  Se ho capito bene, le variazioni standard sono 0,1,-1. 
C'è quindi un problema in questo coefficiente  highscale

https://github.com/niclaurenti/adani/blob/059b15b642e2d12978301280904079d20872850a/src/MatchingConditions.cc#L150

```
} else if (v == -1) { // Updated version w.r.t v==-12 
```
dovrebbe risolvere il problema. Anche il caso della media va sistemato con -1.

**Comment by niclaurenti** [comment]
> @niclaurenti Se ho capito bene, le variazioni standard sono 0,1,-1. C'è quindi un problema in questo coefficiente highscale
> 
> https://github.com/niclaurenti/adani/blob/059b15b642e2d12978301280904079d20872850a/src/MatchingConditions.cc#L150
> 
> ```
> } else if (v == -1) { // Updated version w.r.t v==-12 
> ```
> 
> dovrebbe risolvere il problema. Anche il caso della media va sistemato con -1.

Sì vero hai ragione.
Domani lo sistemo.

Grazie!!
